server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:8090/mem:test
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: 3.37.62.176:9092
    #    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-neighbor

##User defined Properties
kafka:
    topic: groupJoin-events
#  topic: embedded-test-topic
