spring:
  kafka:
    bootstrap-servers: 3.37.62.176:9092
    consumer:
      group-id: my-neighbor
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
## User defined Properties
kafka:
  topic: groupJoin-events
