# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: # 워크플로우를 실행시키는 조건
  pull_request:
    branches: [ "main" ] # main 브랜치에 pr 될 때마다

jobs: # job: 처리 단위
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # 사용하는 액션, runner 에서 repo 사본 다운로드
    - name: Set up JDK 11
      uses: actions/setup-java@v3 
      with:
        java-version: '11'
        distribution: 'temurin' # 해당 jdk vendor 에서 java 11 구성
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    # test 용 현재 시간 출력

    - name: Get current time
      uses: josStorer/get-current-time@v2.0.2
      id: current-time
      with:
        utcOffset: "+09:00"
    - name: Use current time
      env:
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
      run: echo $R_TIME
      
